.mode csv
.import 'mimicdata/ADMISSIONS.csv' ADMISSIONS_OLD
.import 'mimicdata/CALLOUT.csv' CALLOUT_OLD
.import 'mimicdata/CAREGIVERS.csv' CAREGIVERS_OLD
.import 'mimicdata/CHARTEVENTS.csv' CHARTEVENTS_OLD
.import 'mimicdata/CPTEVENTS.csv' CPTEVENTS_OLD
.import 'mimicdata/D_CPT.csv' D_CPT_OLD
.import 'mimicdata/D_ICD_DIAGNOSES.csv' D_ICD_DIAGNOSES_OLD
.import 'mimicdata/D_ICD_PROCEDURES.csv' D_ICD_PROCEDURES_OLD
.import 'mimicdata/D_ITEMS.csv' D_ITEMS_OLD
.import 'mimicdata/D_LABITEMS.csv' D_LABITEMS_OLD
.import 'mimicdata/DATETIMEEVENTS.csv' DATETIMEEVENTS_OLD
.import 'mimicdata/DIAGNOSES_ICD.csv' DIAGNOSES_ICD_OLD
.import 'mimicdata/DRGCODES.csv' DRGCODES_OLD
.import 'mimicdata/ICUSTAYS.csv' ICUSTAYS_OLD
.import 'mimicdata/INPUTEVENTS_CV.csv' INPUTEVENTS_CV_OLD
.import 'mimicdata/INPUTEVENTS_MV.csv' INPUTEVENTS_MV_OLD
.import 'mimicdata/LABEVENTS.csv' LABEVENTS_OLD
.import 'mimicdata/MICROBIOLOGYEVENTS.csv' MICROBIOLOGYEVENTS_OLD
.import 'mimicdata/NOTEEVENTS.csv' NOTEEVENTS_OLD
.import 'mimicdata/OUTPUTEVENTS.csv' OUTPUTEVENTS_OLD
.import 'mimicdata/PATIENTS.csv' PATIENTS_OLD
.import 'mimicdata/PRESCRIPTIONS.csv' PRESCRIPTIONS_OLD
.import 'mimicdata/PROCEDUREEVENTS_MV.csv' PROCEDUREEVENTS_MV_OLD
.import 'mimicdata/PROCEDURES_ICD.csv' PROCEDURES_ICD_OLD
.import 'mimicdata/SERVICES.csv' SERVICES_OLD
.import 'mimicdata/TRANSFERS.csv' TRANSFERS_OLD

--The previous script assumes all field types are text
-- However, since SQLite does NOT support modifying column type
-- We have to recreate the tables with the correct column types according to the documentation:
-- https://mit-lcp.github.io/mimic-omop/schemaspy-mimic/tables/admissions.html

CREATE TABLE ADMISSIONS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ADMITTIME" TIMESTAMP,
  "DISCHTIME" TIMESTAMP,
  "DEATHTIME" TIMESTAMP,
  "ADMISSION_TYPE" TEXT,
  "ADMISSION_LOCATION" TEXT,
  "DISCHARGE_LOCATION" TEXT,
  "INSURANCE" TEXT,
  "LANGUAGE" TEXT,
  "RELIGION" TEXT,
  "MARITAL_STATUS" TEXT,
  "ETHNICITY" TEXT,
  "EDREGTIME" TIMESTAMP,
  "EDOUTTIME" TIMESTAMP,
  "DIAGNOSIS" TEXT,
  "HOSPITAL_EXPIRE_FLAG" INTEGER,
  "HAS_CHARTEVENTS_DATA" INTEGER
);

INSERT INTO ADMISSIONS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ADMITTIME", "DISCHTIME", "DEATHTIME", "ADMISSION_TYPE", "ADMISSION_LOCATION", "DISCHARGE_LOCATION", "INSURANCE", "LANGUAGE", "RELIGION", "MARITAL_STATUS",
"ETHNICITY", "EDREGTIME", "EDOUTTIME", "DIAGNOSIS", "HOSPITAL_EXPIRE_FLAG", "HAS_CHARTEVENTS_DATA")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ADMITTIME", "DISCHTIME", "DEATHTIME", "ADMISSION_TYPE", "ADMISSION_LOCATION", "DISCHARGE_LOCATION", "INSURANCE", "LANGUAGE", "RELIGION", "MARITAL_STATUS",
"ETHNICITY", "EDREGTIME", "EDOUTTIME", "DIAGNOSIS", "HOSPITAL_EXPIRE_FLAG", "HAS_CHARTEVENTS_DATA"
FROM ADMISSIONS_OLD;


CREATE TABLE CALLOUT(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "SUBMIT_WARDID" INTEGER,
  "SUBMIT_CAREUNIT" TEXT,
  "CURR_WARDID" INTEGER,
  "CURR_CAREUNIT" TEXT,
  "CALLOUT_WARDID" INTEGER,
  "CALLOUT_SERVICE" TEXT,
  "REQUEST_TELE" INTEGER,
  "REQUEST_RESP" INTEGER,
  "REQUEST_CDIFF" INTEGER,
  "REQUEST_MRSA" INTEGER,
  "REQUEST_VRE" INTEGER,
  "CALLOUT_STATUS" TEXT,
  "CALLOUT_OUTCOME" TEXT,
  "DISCHARGE_WARDID" INTEGER,
  "ACKNOWLEDGE_STATUS" TEXT,
  "CREATETIME" TIMESTAMP,
  "UPDATETIME" TIMESTAMP,
  "ACKNOWLEDGETIME" TIMESTAMP,
  "OUTCOMETIME" TIMESTAMP,
  "FIRSTRESERVATIONTIME" TIMESTAMP,
  "CURRENTRESERVATIONTIME" TIMESTAMP
);

INSERT INTO CALLOUT("ROW_ID", "SUBJECT_ID", "HADM_ID", "SUBMIT_WARDID", "SUBMIT_CAREUNIT", "CURR_WARDID", "CURR_CAREUNIT", "CALLOUT_WARDID", "CALLOUT_SERVICE", "REQUEST_TELE", "REQUEST_RESP", "REQUEST_CDIFF",
"REQUEST_MRSA", "REQUEST_VRE", "CALLOUT_STATUS", "CALLOUT_OUTCOME", "DISCHARGE_WARDID", "ACKNOWLEDGE_STATUS", "CREATETIME", "UPDATETIME", "ACKNOWLEDGETIME", "OUTCOMETIME", "FIRSTRESERVATIONTIME",
"CURRENTRESERVATIONTIME")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "SUBMIT_WARDID", "SUBMIT_CAREUNIT", "CURR_WARDID", "CURR_CAREUNIT", "CALLOUT_WARDID", "CALLOUT_SERVICE", "REQUEST_TELE", "REQUEST_RESP", "REQUEST_CDIFF",
"REQUEST_MRSA", "REQUEST_VRE", "CALLOUT_STATUS", "CALLOUT_OUTCOME", "DISCHARGE_WARDID", "ACKNOWLEDGE_STATUS", "CREATETIME", "UPDATETIME", "ACKNOWLEDGETIME", "OUTCOMETIME", "FIRSTRESERVATIONTIME",
"CURRENTRESERVATIONTIME"
FROM CALLOUT_OLD;

CREATE TABLE CAREGIVERS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "CGID" INTEGER,
  "LABEL" TEXT,
  "DESCRIPTION" TEXT
);

INSERT INTO CAREGIVERS("ROW_ID", "CGID", "LABEL", "DESCRIPTION")
SELECT "ROW_ID", "CGID", "LABEL", "DESCRIPTION"
FROM CAREGIVERS_OLD;

CREATE TABLE CHARTEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "ITEMID" INTEGER,
  "CHARTTIME" TIMESTAMP,
  "STORETIME" TIMESTAMP,
  "CGID" INTEGER,
  "VALUE" TEXT,
  "VALUENUM" NUMERIC,
  "VALUEUOM" TEXT,
  "WARNING" INTEGER,
  "ERROR" INTEGER,
  "RESULTSTATUS" TEXT,
  "STOPPED" TEXT
);

INSERT INTO CHARTEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "ITEMID", "CHARTTIME", "STORETIME", "CGID", "VALUE", "VALUENUM", "VALUEUOM", "WARNING", "ERROR", "RESULTSTATUS", "STOPPED")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "ITEMID", "CHARTTIME", "STORETIME", "CGID", "VALUE", "VALUENUM", "VALUEUOM", "WARNING", "ERROR", "RESULTSTATUS", "STOPPED"
FROM CHARTEVENTS_OLD;

CREATE TABLE CPTEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "COSTCENTER" TEXT,
  "CHARTDATE" TIMESTAMP,
  "CPT_CD" TEXT,
  "CPT_NUMBER" INTEGER,
  "CPT_SUFFIX" TEXT,
  "TICKET_ID_SEQ" INTEGER,
  "SECTIONHEADER" TEXT,
  "SUBSECTIONHEADER" TEXT,
  "DESCRIPTION" TEXT
);

INSERT INTO CPTEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "COSTCENTER", "CHARTDATE", "CPT_CD", "CPT_NUMBER", "CPT_SUFFIX", "TICKET_ID_SEQ", "SECTIONHEADER", "SUBSECTIONHEADER", "DESCRIPTION")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "COSTCENTER", "CHARTDATE", "CPT_CD", "CPT_NUMBER", "CPT_SUFFIX", "TICKET_ID_SEQ", "SECTIONHEADER", "SUBSECTIONHEADER", "DESCRIPTION"
FROM CPTEVENTS_OLD;

CREATE TABLE D_CPT(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "CATEGORY" INTEGER,
  "SECTIONRANGE" TEXT,
  "SECTIONHEADER" TEXT,
  "SUBSECTIONRANGE" TEXT,
  "SUBSECTIONHEADER" TEXT,
  "CODESUFFIX" TEXT,
  "MINCODEINSUBSECTION" INTEGER,
  "MAXCODEINSUBSECTION" INTEGER
);

INSERT INTO D_CPT("ROW_ID", "CATEGORY", "SECTIONRANGE", "SECTIONHEADER", "SUBSECTIONRANGE", "SUBSECTIONHEADER", "CODESUFFIX", "MINCODEINSUBSECTION", "MAXCODEINSUBSECTION")
SELECT "ROW_ID", "CATEGORY", "SECTIONRANGE", "SECTIONHEADER", "SUBSECTIONRANGE", "SUBSECTIONHEADER", "CODESUFFIX", "MINCODEINSUBSECTION", "MAXCODEINSUBSECTION"
FROM D_CPT_OLD;

CREATE TABLE D_ICD_DIAGNOSES(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "ICD9_CODE" TEXT,
  "SHORT_TITLE" TEXT,
  "LONG_TITLE" TEXT
);

INSERT INTO D_ICD_DIAGNOSES("ROW_ID", "ICD9_CODE", "SHORT_TITLE", "LONG_TITLE")
SELECT "ROW_ID", "ICD9_CODE", "SHORT_TITLE", "LONG_TITLE"
FROM D_ICD_DIAGNOSES_OLD;

CREATE TABLE D_ICD_PROCEDURES(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "ICD9_CODE" TEXT,
  "SHORT_TITLE" TEXT,
  "LONG_TITLE" TEXT
);

INSERT INTO D_ICD_PROCEDURES("ROW_ID", "ICD9_CODE", "SHORT_TITLE", "LONG_TITLE")
SELECT "ROW_ID", "ICD9_CODE", "SHORT_TITLE", "LONG_TITLE"
FROM D_ICD_PROCEDURES_OLD;

CREATE TABLE D_ITEMS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "ITEMID" INTEGER,
  "LABEL" TEXT,
  "ABBREVIATION" TEXT,
  "DBSOURCE" TEXT,
  "LINKSTO" TEXT,
  "CATEGORY" TEXT,
  "UNITNAME" TEXT,
  "PARAM_TYPE" TEXT,
  "CONCEPTID" INTEGER
);

INSERT INTO D_ITEMS("ROW_ID", "ITEMID", "LABEL", "ABBREVIATION", "DBSOURCE", "LINKSTO", "CATEGORY", "UNITNAME", "PARAM_TYPE", "CONCEPTID")
SELECT "ROW_ID", "ITEMID", "LABEL", "ABBREVIATION", "DBSOURCE", "LINKSTO", "CATEGORY", "UNITNAME", "PARAM_TYPE", "CONCEPTID"
FROM D_ITEMS_OLD;

CREATE TABLE D_LABITEMS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "ITEMID" INTEGER,
  "LABEL" TEXT,
  "FLUID" TEXT,
  "CATEGORY" TEXT,
  "LOINC_CODE" TEXT
);

INSERT INTO D_LABITEMS("ROW_ID", "ITEMID", "LABEL", "FLUID", "CATEGORY", "LOINC_CODE")
SELECT "ROW_ID", "ITEMID", "LABEL", "FLUID", "CATEGORY", "LOINC_CODE"
FROM D_LABITEMS_OLD;

CREATE TABLE DATETIMEEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "ITEMID" INTEGER,
  "CHARTTIME" TIMESTAMP,
  "STORETIME" TIMESTAMP,
  "CGID" INTEGER,
  "VALUE" TIMESTAMP,
  "VALUEUOM" TEXT,
  "WARNING" INTEGER,
  "ERROR" INTEGER,
  "RESULTSTATUS" TEXT,
  "STOPPED" TEXT
);

INSERT INTO DATETIMEEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "ITEMID", "CHARTTIME", "STORETIME", "CGID", "VALUE", "VALUEUOM", "WARNING", "ERROR", "RESULTSTATUS", "STOPPED")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "ITEMID", "CHARTTIME", "STORETIME", "CGID", "VALUE", "VALUEUOM", "WARNING", "ERROR", "RESULTSTATUS", "STOPPED"
FROM DATETIMEEVENTS_OLD;

CREATE TABLE DIAGNOSES_ICD(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "SEQ_NUM" INTEGER,
  "ICD9_CODE" TEXT
);

INSERT INTO DIAGNOSES_ICD("ROW_ID", "SUBJECT_ID", "HADM_ID", "SEQ_NUM", "ICD9_CODE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "SEQ_NUM", "ICD9_CODE"
FROM DIAGNOSES_ICD_OLD;

CREATE TABLE DRGCODES(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "DRG_TYPE" TEXT,
  "DRG_CODE" TEXT,
  "DESCRIPTION" TEXT,
  "DRG_SEVERITY" INTEGER,
  "DRG_MORTALITY" INTEGER
);

INSERT INTO DRGCODES("ROW_ID", "SUBJECT_ID", "HADM_ID", "DRG_TYPE", "DRG_CODE", "DESCRIPTION", "DRG_SEVERITY", "DRG_MORTALITY")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "DRG_TYPE", "DRG_CODE", "DESCRIPTION", "DRG_SEVERITY", "DRG_MORTALITY"
FROM DRGCODES_OLD;

CREATE TABLE ICUSTAYS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "DBSOURCE" TEXT,
  "FIRST_CAREUNIT" TEXT,
  "LAST_CAREUNIT" TEXT,
  "FIRST_WARDID" INTEGER,
  "LAST_WARDID" INTEGER,
  "INTIME" TIMESTAMP,
  "OUTTIME" TIMESTAMP,
  "LOS" NUMERIC
);

INSERT INTO ICUSTAYS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "DBSOURCE", "FIRST_CAREUNIT", "LAST_CAREUNIT", "FIRST_WARDID", "LAST_WARDID", "INTIME", "OUTTIME", "LOS")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "DBSOURCE", "FIRST_CAREUNIT", "LAST_CAREUNIT", "FIRST_WARDID", "LAST_WARDID", "INTIME", "OUTTIME", "LOS"
FROM ICUSTAYS_OLD;

CREATE TABLE INPUTEVENTS_CV(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "CHARTTIME" TIMESTAMP,
  "ITEMID" INTEGER,
  "AMOUNT" NUMERIC,
  "AMOUNTUOM" TEXT,
  "RATE" NUMERIC,
  "RATEUOM" TEXT,
  "STORETIME" TIMESTAMP,
  "CGID" INTEGER,
  "ORDERID" INTEGER,
  "LINKORDERID" INTEGER,
  "STOPPED" TEXT,
  "NEWBOTTLE" INTEGER,
  "ORIGINALAMOUNT" NUMERIC,
  "ORIGINALAMOUNTUOM" TEXT,
  "ORIGINALROUTE" TEXT,
  "ORIGINALRATE" NUMERIC,
  "ORIGINALRATEUOM" TEXT,
  "ORIGINALSITE" TEXT
);

INSERT INTO INPUTEVENTS_CV("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "CHARTTIME", "ITEMID", "AMOUNT", "AMOUNTUOM", "RATE", "RATEUOM", "STORETIME", "CGID", "ORDERID", "LINKORDERID", "STOPPED",
"NEWBOTTLE", "ORIGINALAMOUNT", "ORIGINALAMOUNTUOM", "ORIGINALROUTE", "ORIGINALRATE", "ORIGINALRATEUOM", "ORIGINALSITE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "CHARTTIME", "ITEMID", "AMOUNT", "AMOUNTUOM", "RATE", "RATEUOM", "STORETIME", "CGID", "ORDERID", "LINKORDERID", "STOPPED",
"NEWBOTTLE", "ORIGINALAMOUNT", "ORIGINALAMOUNTUOM", "ORIGINALROUTE", "ORIGINALRATE", "ORIGINALRATEUOM", "ORIGINALSITE"
FROM INPUTEVENTS_CV_OLD;

CREATE TABLE INPUTEVENTS_MV(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "STARTTIME" TIMESTAMP,
  "ENDTIME" TIMESTAMP,
  "ITEMID" INTEGER,
  "AMOUNT" NUMERIC,
  "AMOUNTUOM" TEXT,
  "RATE" NUMERIC,
  "RATEUOM" TEXT,
  "STORETIME" TIMESTAMP,
  "CGID" INTEGER,
  "ORDERID" INTEGER,
  "LINKORDERID" INTEGER,
  "ORDERCATEGORYNAME" TEXT,
  "SECONDARYORDERCATEGORYNAME" TEXT,
  "ORDERCOMPONENTTYPEDESCRIPTION" TEXT,
  "ORDERCATEGORYDESCRIPTION" TEXT,
  "PATIENTWEIGHT" NUMERIC,
  "TOTALAMOUNT" NUMERIC,
  "TOTALAMOUNTUOM" TEXT,
  "ISOPENBAG" INTEGER,
  "CONTINUEINNEXTDEPT" INTEGER,
  "CANCELREASON" INTEGER,
  "STATUSDESCRIPTION" TEXT,
  "COMMENTS_EDITEDBY" TEXT,
  "COMMENTS_CANCELEDBY" TEXT,
  "COMMENTS_DATE" TIMESTAMP,
  "ORIGINALAMOUNT" NUMERIC,
  "ORIGINALRATE" NUMERIC
);

INSERT INTO INPUTEVENTS_MV("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "STARTTIME", "ENDTIME", "ITEMID", "AMOUNT", "AMOUNTUOM", "RATE", "RATEUOM", "STORETIME", "CGID", "ORDERID", "LINKORDERID",
"ORDERCATEGORYNAME", "SECONDARYORDERCATEGORYNAME", "ORDERCOMPONENTTYPEDESCRIPTION", "ORDERCATEGORYDESCRIPTION", "PATIENTWEIGHT", "TOTALAMOUNT", "TOTALAMOUNTUOM", "ISOPENBAG", "CONTINUEINNEXTDEPT",
"CANCELREASON", "STATUSDESCRIPTION", "COMMENTS_EDITEDBY", "COMMENTS_CANCELEDBY", "COMMENTS_DATE", "ORIGINALAMOUNT", "ORIGINALRATE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "STARTTIME", "ENDTIME", "ITEMID", "AMOUNT", "AMOUNTUOM", "RATE", "RATEUOM", "STORETIME", "CGID", "ORDERID", "LINKORDERID",
"ORDERCATEGORYNAME", "SECONDARYORDERCATEGORYNAME", "ORDERCOMPONENTTYPEDESCRIPTION", "ORDERCATEGORYDESCRIPTION", "PATIENTWEIGHT", "TOTALAMOUNT", "TOTALAMOUNTUOM", "ISOPENBAG", "CONTINUEINNEXTDEPT",
"CANCELREASON", "STATUSDESCRIPTION", "COMMENTS_EDITEDBY", "COMMENTS_CANCELEDBY", "COMMENTS_DATE", "ORIGINALAMOUNT", "ORIGINALRATE"
FROM INPUTEVENTS_MV_OLD;

CREATE TABLE LABEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ITEMID" INTEGER,
  "CHARTTIME" TIMESTAMP,
  "VALUE" TEXT,
  "VALUENUM" NUMERIC,
  "VALUEUOM" TEXT,
  "FLAG" TEXT
);

INSERT INTO LABEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ITEMID", "CHARTTIME", "VALUE", "VALUENUM", "VALUEUOM", "FLAG")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ITEMID", "CHARTTIME", "VALUE", "VALUENUM", "VALUEUOM", "FLAG"
FROM LABEVENTS_OLD;

CREATE TABLE MICROBIOLOGYEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "CHARTDATE" TIMESTAMP,
  "CHARTTIME" TIMESTAMP,
  "SPEC_ITEMID" INTEGER,
  "SPEC_TYPE_DESC" TEXT,
  "ORG_ITEMID" INTEGER,
  "ORG_NAME" TEXT,
  "ISOLATE_NUM" INTEGER,
  "AB_ITEMID" INTEGER,
  "AB_NAME" TEXT,
  "DILUTION_TEXT" TEXT,
  "DILUTION_COMPARISON" TEXT,
  "DILUTION_VALUE" NUMERIC,
  "INTERPRETATION" TEXT
);

INSERT INTO MICROBIOLOGYEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "CHARTDATE", "CHARTTIME", "SPEC_ITEMID", "SPEC_TYPE_DESC", "ORG_ITEMID", "ORG_NAME", "ISOLATE_NUM", "AB_ITEMID", "AB_NAME",
"DILUTION_TEXT", "DILUTION_COMPARISON", "DILUTION_VALUE", "INTERPRETATION")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "CHARTDATE", "CHARTTIME", "SPEC_ITEMID", "SPEC_TYPE_DESC", "ORG_ITEMID", "ORG_NAME", "ISOLATE_NUM", "AB_ITEMID", "AB_NAME",
"DILUTION_TEXT", "DILUTION_COMPARISON", "DILUTION_VALUE", "INTERPRETATION"
FROM MICROBIOLOGYEVENTS_OLD;

CREATE TABLE NOTEEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "CHARTDATE" TIMESTAMP,
  "CHARTTIME" TIMESTAMP,
  "STORETIME" TIMESTAMP,
  "CATEGORY" TEXT,
  "DESCRIPTION" TEXT,
  "CGID" INTEGER,
  "ISERROR" TEXT,
  "TEXT" TEXT
);

INSERT INTO NOTEEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "CHARTDATE", "CHARTTIME", "STORETIME", "CATEGORY", "DESCRIPTION", "CGID", "ISERROR", "TEXT")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "CHARTDATE", "CHARTTIME", "STORETIME", "CATEGORY", "DESCRIPTION", "CGID", "ISERROR", "TEXT"
FROM NOTEEVENTS_OLD;

CREATE TABLE OUTPUTEVENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "CHARTTIME" TIMESTAMP,
  "ITEMID" INTEGER,
  "VALUE" NUMERIC,
  "VALUEUOM" TEXT,
  "STORETIME" TIMESTAMP,
  "CGID" INTEGER,
  "STOPPED" TEXT,
  "NEWBOTTLE" TEXT,
  "ISERROR" INTEGER
);

INSERT INTO OUTPUTEVENTS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "CHARTTIME", "ITEMID", "VALUE", "VALUEUOM", "STORETIME", "CGID", "STOPPED", "NEWBOTTLE", "ISERROR")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "CHARTTIME", "ITEMID", "VALUE", "VALUEUOM", "STORETIME", "CGID", "STOPPED", "NEWBOTTLE", "ISERROR"
FROM OUTPUTEVENTS_OLD;

CREATE TABLE PATIENTS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "GENDER" TEXT,
  "DOB" TIMESTAMP,
  "DOD" TIMESTAMP,
  "DOD_HOSP" TIMESTAMP,
  "DOD_SSN" TIMESTAMP,
  "EXPIRE_FLAG" INTEGER
);

INSERT INTO PATIENTS("ROW_ID", "SUBJECT_ID", "GENDER", "DOB", "DOD", "DOD_HOSP", "DOD_SSN", "EXPIRE_FLAG")
SELECT "ROW_ID", "SUBJECT_ID", "GENDER", "DOB", "DOD", "DOD_HOSP", "DOD_SSN", "EXPIRE_FLAG"
FROM PATIENTS_OLD;

CREATE TABLE PRESCRIPTIONS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "STARTDATE" TIMESTAMP,
  "ENDDATE" TIMESTAMP,
  "DRUG_TYPE" TEXT,
  "DRUG" TEXT,
  "DRUG_NAME_POE" TEXT,
  "DRUG_NAME_GENERIC" TEXT,
  "FORMULARY_DRUG_CD" TEXT,
  "GSN" TEXT,
  "NDC" TEXT,
  "PROD_STRENGTH" TEXT,
  "DOSE_VAL_RX" TEXT,
  "DOSE_UNIT_RX" TEXT,
  "FORM_VAL_DISP" TEXT,
  "FORM_UNIT_DISP" TEXT,
  "ROUTE" TEXT
);

INSERT INTO PRESCRIPTIONS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "STARTDATE", "ENDDATE", "DRUG_TYPE", "DRUG", "DRUG_NAME_POE", "DRUG_NAME_GENERIC", "FORMULARY_DRUG_CD", "GSN", "NDC",
"PROD_STRENGTH", "DOSE_VAL_RX", "DOSE_UNIT_RX", "FORM_VAL_DISP", "FORM_UNIT_DISP", "ROUTE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "STARTDATE", "ENDDATE", "DRUG_TYPE", "DRUG", "DRUG_NAME_POE", "DRUG_NAME_GENERIC", "FORMULARY_DRUG_CD", "GSN", "NDC",
"PROD_STRENGTH", "DOSE_VAL_RX", "DOSE_UNIT_RX", "FORM_VAL_DISP", "FORM_UNIT_DISP", "ROUTE"
FROM PRESCRIPTIONS_OLD;

CREATE TABLE PROCEDUREEVENTS_MV(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "STARTTIME" TIMESTAMP,
  "ENDTIME" TIMESTAMP,
  "ITEMID" INTEGER,
  "VALUE" NUMERIC,
  "VALUEUOM" TEXT,
  "LOCATION" TEXT,
  "LOCATIONCATEGORY" TEXT,
  "STORETIME" TIMESTAMP,
  "CGID" INTEGER,
  "ORDERID" INTEGER,
  "LINKORDERID" INTEGER,
  "ORDERCATEGORYNAME" TEXT,
  "SECONDARYORDERCATEGORYNAME" TEXT,
  "ORDERCATEGORYDESCRIPTION" TEXT,
  "ISOPENBAG" INTEGER,
  "CONTINUEINNEXTDEPT" INTEGER,
  "CANCELREASON" INTEGER,
  "STATUSDESCRIPTION" TEXT,
  "COMMENTS_EDITEDBY" TEXT,
  "COMMENTS_CANCELEDBY" TEXT,
  "COMMENTS_DATE" TIMESTAMP
);

INSERT INTO PROCEDUREEVENTS_MV("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "STARTTIME", "ENDTIME", "ITEMID", "VALUE", "VALUEUOM", "LOCATION", "LOCATIONCATEGORY", "STORETIME", "CGID", "ORDERID",
"LINKORDERID", "ORDERCATEGORYNAME", "SECONDARYORDERCATEGORYNAME", "ORDERCATEGORYDESCRIPTION", "ISOPENBAG", "CONTINUEINNEXTDEPT", "CANCELREASON", "STATUSDESCRIPTION", "COMMENTS_EDITEDBY",
"COMMENTS_CANCELEDBY", "COMMENTS_DATE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "STARTTIME", "ENDTIME", "ITEMID", "VALUE", "VALUEUOM", "LOCATION", "LOCATIONCATEGORY", "STORETIME", "CGID", "ORDERID",
"LINKORDERID", "ORDERCATEGORYNAME", "SECONDARYORDERCATEGORYNAME", "ORDERCATEGORYDESCRIPTION", "ISOPENBAG", "CONTINUEINNEXTDEPT", "CANCELREASON", "STATUSDESCRIPTION", "COMMENTS_EDITEDBY",
"COMMENTS_CANCELEDBY", "COMMENTS_DATE"
FROM PROCEDUREEVENTS_MV_OLD;

CREATE TABLE PROCEDURES_ICD(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "SEQ_NUM" INTEGER,
  "ICD9_CODE" TEXT
);

INSERT INTO PROCEDURES_ICD("ROW_ID", "SUBJECT_ID", "HADM_ID", "SEQ_NUM", "ICD9_CODE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "SEQ_NUM", "ICD9_CODE"
FROM PROCEDURES_ICD_OLD;

CREATE TABLE SERVICES(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "TRANSFERTIME" TIMESTAMP,
  "PREV_SERVICE" TEXT,
  "CURR_SERVICE" TEXT
);

INSERT INTO SERVICES("ROW_ID", "SUBJECT_ID", "HADM_ID", "TRANSFERTIME", "PREV_SERVICE", "CURR_SERVICE")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "TRANSFERTIME", "PREV_SERVICE", "CURR_SERVICE"
FROM SERVICES_OLD;

CREATE TABLE TRANSFERS(
  "MIMIC_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ROW_ID" INTEGER,
  "SUBJECT_ID" INTEGER,
  "HADM_ID" INTEGER,
  "ICUSTAY_ID" INTEGER,
  "DBSOURCE" TEXT,
  "EVENTTYPE" TEXT,
  "PREV_CAREUNIT" TEXT,
  "CURR_CAREUNIT" TEXT,
  "PREV_WARDID" INTEGER,
  "CURR_WARDID" INTEGER,
  "INTIME" TIMESTAMP,
  "OUTTIME" TIMESTAMP,
  "LOS" NUMERIC
);

INSERT INTO TRANSFERS("ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "DBSOURCE", "EVENTTYPE", "PREV_CAREUNIT", "CURR_CAREUNIT", "PREV_WARDID", "CURR_WARDID", "INTIME", "OUTTIME", "LOS")
SELECT "ROW_ID", "SUBJECT_ID", "HADM_ID", "ICUSTAY_ID", "DBSOURCE", "EVENTTYPE", "PREV_CAREUNIT", "CURR_CAREUNIT", "PREV_WARDID", "CURR_WARDID", "INTIME", "OUTTIME", "LOS"
FROM TRANSFERS_OLD;

DROP TABLE ADMISSIONS_OLD;
DROP TABLE CALLOUT_OLD;
DROP TABLE CAREGIVERS_OLD;
DROP TABLE CHARTEVENTS_OLD;
DROP TABLE CPTEVENTS_OLD;
DROP TABLE D_CPT_OLD;
DROP TABLE D_ICD_DIAGNOSES_OLD;
DROP TABLE D_ICD_PROCEDURES_OLD;
DROP TABLE D_ITEMS_OLD;
DROP TABLE D_LABITEMS_OLD;
DROP TABLE DATETIMEEVENTS_OLD;
DROP TABLE DIAGNOSES_ICD_OLD;
DROP TABLE DRGCODES_OLD;
DROP TABLE ICUSTAYS_OLD;
DROP TABLE INPUTEVENTS_CV_OLD;
DROP TABLE INPUTEVENTS_MV_OLD;
DROP TABLE LABEVENTS_OLD;
DROP TABLE MICROBIOLOGYEVENTS_OLD;
DROP TABLE NOTEEVENTS_OLD;
DROP TABLE OUTPUTEVENTS_OLD;
DROP TABLE PATIENTS_OLD;
DROP TABLE PRESCRIPTIONS_OLD;
DROP TABLE PROCEDUREEVENTS_MV_OLD;
DROP TABLE PROCEDURES_ICD_OLD;
DROP TABLE SERVICES_OLD;
DROP TABLE TRANSFERS_OLD;

-- For the following tables, mimic_id should start from 1
-- NOTE: admissions table already has its mimic-id column updated
UPDATE callout SET mimic_id = mimic_id+(SELECT mimic_id FROM admissions ORDER BY mimic_id DESC LIMIT 1);
UPDATE caregivers SET mimic_id = mimic_id+(SELECT mimic_id FROM callout ORDER BY mimic_id DESC LIMIT 1);

UPDATE chartevents SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE chartevents SET mimic_id = mimic_id+(SELECT mimic_id FROM caregivers ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE cptevents SET mimic_id = mimic_id+(SELECT mimic_id FROM chartevents ORDER BY mimic_id DESC LIMIT 1);

UPDATE datetimeevents SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE datetimeevents SET mimic_id = mimic_id+(SELECT mimic_id FROM cptevents ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE diagnoses_icd SET mimic_id = mimic_id+(SELECT mimic_id FROM datetimeevents ORDER BY mimic_id DESC LIMIT 1);
UPDATE drgcodes SET mimic_id = mimic_id+(SELECT mimic_id FROM diagnoses_icd ORDER BY mimic_id DESC LIMIT 1);
UPDATE icustays SET mimic_id = mimic_id+(SELECT mimic_id FROM drgcodes ORDER BY mimic_id DESC LIMIT 1);

UPDATE inputevents_cv SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE inputevents_cv SET mimic_id = mimic_id+(SELECT mimic_id FROM icustays ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE inputevents_mv SET mimic_id = mimic_id+(SELECT mimic_id FROM inputevents_cv ORDER BY mimic_id DESC LIMIT 1);

UPDATE labevents SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE labevents SET mimic_id = mimic_id+(SELECT mimic_id FROM inputevents_mv ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE microbiologyevents SET mimic_id = mimic_id+(SELECT mimic_id FROM labevents ORDER BY mimic_id DESC LIMIT 1);

UPDATE noteevents SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE noteevents SET mimic_id = mimic_id+(SELECT mimic_id FROM microbiologyevents ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE outputevents SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE outputevents SET mimic_id = mimic_id+(SELECT mimic_id FROM noteevents ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE patients SET mimic_id = mimic_id+(SELECT mimic_id FROM outputevents ORDER BY mimic_id DESC LIMIT 1);

UPDATE prescriptions SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE prescriptions SET mimic_id = mimic_id+(SELECT mimic_id FROM patients ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE procedureevents_mv SET mimic_id = mimic_id+(SELECT mimic_id FROM prescriptions ORDER BY mimic_id DESC LIMIT 1);
UPDATE procedures_icd SET mimic_id = mimic_id+(SELECT mimic_id FROM procedureevents_mv ORDER BY mimic_id DESC LIMIT 1);
UPDATE services SET mimic_id = mimic_id+(SELECT mimic_id FROM procedures_icd ORDER BY mimic_id DESC LIMIT 1);

UPDATE transfers SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE transfers SET mimic_id = mimic_id+(SELECT mimic_id FROM services ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value


--For the following tables, mimic_id should start with 2001000000
UPDATE d_icd_diagnoses SET mimic_id = mimic_id+2000999999;
UPDATE d_icd_procedures SET mimic_id = mimic_id+(SELECT mimic_id FROM d_icd_diagnoses ORDER BY mimic_id DESC LIMIT 1);

UPDATE d_items SET mimic_id = mimic_id+3000000000; --We set a temporary value to avoid UNIQUE constraint error
UPDATE d_items SET mimic_id = mimic_id+(SELECT mimic_id FROM d_icd_procedures ORDER BY mimic_id DESC LIMIT 1)-3000000000; --We remove that temporary value

UPDATE d_labitems SET mimic_id = mimic_id+(SELECT mimic_id FROM d_items ORDER BY mimic_id DESC LIMIT 1);
UPDATE d_cpt SET mimic_id = mimic_id+(SELECT mimic_id FROM d_labitems ORDER BY mimic_id DESC LIMIT 1);


--CREATE A TEMPORARY TABLE FOR THE SEQUENCES

CREATE TABLE TEMP_SEQUENCES(
  mimic_id_seq INTEGER,
  mimic_id_concept_seq INTEGER
);

--UPDATE THE PREVIOUS SEQUENCE
INSERT INTO TEMP_SEQUENCES VALUES((SELECT mimic_id FROM transfers ORDER BY mimic_id DESC LIMIT 1), (SELECT mimic_id FROM d_cpt ORDER BY mimic_id DESC LIMIT 1));

.exit